version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1401:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyS3cr3t@Passwort!

  quiz-app-backend:
    build: .
    restart: unless-stopped
    ports:
      - "9009:9009"
    environment:
      - DB_CONNECTION_STRING=jdbc:sqlserver://ms-sql-server:1433;database=Master;user=SA;password=MyS3cr3t@Passwort!;encrypt=false;loginTimeout=30;
      - JWT_ISSUER=MyIssuer
      - JWT_SECRET_KEY=MyPassword
    links:
      - ms-sql-server
